### ISSUE TITLE
Documentation checklist

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#1128]
A checklist for missing/not up-to-date docs.

- [x] Tickers and formatters #524
- [x] AR #1060 
- [ ] Gallery indexing #1032 
- [x] Charts #983 
- [ ] BEP 3: Documentation process and guidelines #1007 
- [x] Dev setup instructions #950 
- [x] ColumnDataSource #946 
- [x] Axis, axis labels and grids #906 #850
- [x] Spectogram demo #883 
- [x] Widgets #853 
- [x] BokehJS API #825 
- [x] Dev guide #754 
- [x] Bokeh Server #1170

Feel free to add more items to the list if you feel there is something else missing.

**Comment by bryevdv** [comment]
We should at least chip away some of this for 0.8

**Comment by bryevdv** [comment]
This has served its purpose.
