### ISSUE TITLE
Bokeh 3.0 Iteration Plan

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#12105]
This document outlines the timeline and tasks to accomplish for Bokeh 3.0 major release.
| Date  | Event |
| ------------- | ------------- |
| 28 Oct 2021 | Bokeh 3.0-dev1 |
| 9 Dec 2021 | Bokeh 3.0-dev2 |
| 6 Jan 2022 | Bokeh 3.0-dev3 |
| 27 Jan 2022 | Bokeh 3.0-dev4 |
| 3 Mar 2022 | Bokeh 3.0-dev5 |
| 27 Apr 2022 | Bokeh 3.0-dev6 |
| 13 Jun 2022 | Bokeh 3.0-dev7 |
| 24 Jun 2022 | Bokeh 3.0-dev8 |
| 1 Jul 2022 | Bokeh 3.0-dev9 |
| 5 Jul 2022 | Bokeh 3.0-dev10 |
| 4 Aug 2022 | Bokeh 3.0-dev11 |
| 8 Aug 2022 | Bokeh 3.0-dev12 |
| 20 Aug 2022 | Bokeh 3.0-dev13 |
| 27 Aug 2022 | Bokeh 3.0-dev14 |
| 3 Sep 2022 | Bokeh 3.0-dev15 |
| 13 Sep 2022 | Bokeh 3.0-dev16 |
| 17 Sep 2022 | Bokeh 3.0-dev17 |
| 17 Sep 2022 | Bokeh 3.0-dev18 |
| 01 Oct 2022 | Bokeh 3.0-dev19 |
| 09 Oct 2022 | Bokeh 3.0-dev20 |
| **11 Oct 2022**  | **Bokeh 3.0 RC1 Release**   |
| **11 Oct 2022**  | **Bokeh 3.0 RC2 Release**   |
| **11 Oct 2022**  | **Bokeh 3.0 RC3 Release**   |
| **19 Oct 2022**  | **Bokeh 3.0 RC4 Release**   |
| **24 Oc 2022**  | **Bokeh 3.0 Final Release**  |

Major features and changes
-------------------------------------

1. [x] **Drop support for legacy (pre ES6) browsers, in particular IE**. Remove polyfills and migrate to modern APIs. Establish minimal viable versions of major web browsers supported by bokehjs. Possibly establish a scheme for rolling phaseout of obsolete versions.
2. [x] **Robustify serialization protocol and related APIs**. Introduce a robust intermediate (serializable) representation. Allow for universal handling of binary buffers. Possibly add support for fully binary protocol.
3. [x] **Modularize bokehjs' CSS**. Migrate to shadow DOM and isolate each bokehjs components' styles. Establish an "API" for defining robust themes for external usage.
4. [x] **Make bokeh's layout interoperate with CSS better.** Respect DOM/CSS instead of working around it. Focus on performance of large dashboards and ease of embedding into existing HTML/CSS.
5. **Robustify in-canvas positioning schemes**. Add support for sub-coordinates and mapping between coordinate systems. Allow multiple plots on a single canvas and arbitrary positioning of frames. (postponed to 3.1)
6. [x] **Further robustify WebGL-based rendering backend**. Focus on the robustness of the implementation and coverage of previously not implemented cases (glyphs, hatch patterns, line joints, etc.).

**Comment by mattpap** [comment]
The remaining sub-tasks to finalize the release:

- [ ] Establish a migration path and/or compatibility mode after CSS modularization (see #12082).
- [ ] Update `jupyter-bokeh` (etc.) after serialization redesign.
- [ ] Finalize layout redesign (#11915).
- [ ] Finalize canvas/positioning redesign (#12083).
