### ISSUE TITLE
Build/Release automation improvements. 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1518]
This issue is meant to collect sub-issues. Each of the bullets below should get its own issue created. 

~~build dev release on binstar~~
~~build full release on binstar~~
* [x] automated CDN uploading for BokehJS #1568
* [x] hosting for dev build BokehJS versions on CDN #1540
* [x] make multiple versions of docs deployable #1609 
* [x] deploy docs for: latest release, previous release, latest dev build #1609, #1771

@damianavila @mattpap please contribute or comment on tasks I want to get a good overall view of the bigger picture before embarking on any of these. 

**EDIT**: We are building devel builds in TravisCI now... all the other bullets described here were solved in multiple separate PRs mentioned in each bullet.

**Comment by damianavila** [comment]
I have update the first post of thi thread, all the items are completed now except for the Binstar ones... for them I will open another issue with the specific needs. Closing here.
