### ISSUE TITLE
Auto document JSON for bokeh.models 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1579]
This will help language binding implementors.
* [x] provide hooks to easily dump models with **all** properties (not just changed ones) (#1580)
* [x] remove unused cruft attributes (#1583)
* [x] write script to integrate all models and their JSON into dev docs (#1581)
