### ISSUE TITLE
Demos for January point release

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#1585]
* [x] Scatter plot with density histograms above/right, and lasso selection driving secondary density histograms (#1593)
* [x] Additional kernels for numba examples (#1594)
* [x] ~~Dynamic linked ranges, either via Python-built checkbox, or built-in feature in BokehJS~~
  * [x] ~~Might be ideal to do cheesy JS-embedding function interface~~
* [x] ~~Stock ticker stream plot~~ (#1595)
* [x] CLI tool examples
  * [x] piping netcat data into bokeh server or plot rendering in IPyNB output cell (#1596)
  * [x] twitter-scraping tool that plops geotagged tweets matching some hashtags as scatter points on a map plot (#1598)
  * [x] interactive filter: pop up plot of all input, allow user to select points, then dump selected points to stdout (#1597)

Edit: @pzwang I added strikethough to things I don't think are feasible for this release.

**Comment by fpliger** [comment]
CLI examples merged in release 0.7.1 have a few differences from what described in this issue:

> piping netcat data into bokeh server or plot rendering in IPyNB output cell (#1596)

We have shipped an example that show CLI streaming data from local file and/or url to a bokeh server (`stream_sys_stats_to_file.sh` and `stream_netfond.sh`). With the current design it was not possible to have also a chart being updated on an external IPyNB.

> twitter-scraping tool that plops geotagged tweets matching some hashtags as scatter points on a map plot (#1598)

There are 2 separated examples of scatter points being generated from a csv file simulating streaming new tweets (`stream_tweets.sh`). There's also an example of a GMap and a scatter charts on the same figure with a static html file output (`stream_tweets_gmap_file.sh`) because is has issues outputing to bokeh-server.

> interactive filter: pop up plot of all input, allow user to select points, then dump selected points to stdout (#1597)

`tweets_smart_filters.sh` shows an example of filtering data from a file source, selecting data and copying selected data to clipboard.

**Comment by bryevdv** [comment]
@pzwang stock ticker will not be *in* the release but I will see if I can bang a script together today that you could run.
