### ISSUE TITLE
Improvements to ticking

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1668]
The ticking system can use several improvements. Some of those concern the choice of ticks and some concern tick formatting:
- [ ] use label text dimensions to inform auto-computation of number of ticks.  (#1669)
- [ ] allow users to specify hard values: min, max, exact numbers of ticks (#1670)
- [x] allow users to specify explicit tick values (#1671)
- [x] ~~mechanism for semantic (re-)labeling of numeric tick values~~ (#1672)
- [x] allow some ticks to have "more detail", e.g.: `12:37       :38       :39        :40       :41` (#1674)
- [x] allow tick formats to be supplied (#842)
- [x] documentation (#524)
- [x] allow users to specify a suggested, desired number of ticks (#2185)

References: #1664

@bokeh/dev any additions to this list welcome

**Comment by kdodia** [comment]
A handful of open issues with relevant discussions:

 - Tickers and formatters have no documentation and examples #524
 - Add axis label formatters (sprintf-style, etc.) #842
 - High Level Charts Disable Scientific #1549

**Comment by bryevdv** [comment]
I've added docs and sprintf formats, I think #1549 falls under some of the other task (formatters, or semantic labeling, depending on how you look at it )

**Comment by bryevdv** [comment]
Most of these are now possible, I am going to close this as a discussion.

**Comment by cjw296** [comment]
@bryevdv - did these changes ever get documented? Can't find much for datetime tick control, particularly minor ticks...

**Comment by bryevdv** [comment]
@cjw296 all the bullets in the issue have associated issues listed, and are checked off (or not). Minor ticks were not part of this group of suggestions, as best I can recall. There is a separate open issue for them though:

https://github.com/bokeh/bokeh/issues/2996

As stated there, the fact that months are uneven raises questions about the utility of minor ticks on a date time scale, or what even exactly they should do in all cases. But I am happy to consider a PR if someone else wants to scratch that itch.

**Comment by bernd-wechner** [comment]
I'd love to see one on the list that looks missing to me: Support a "prevent_tick_label_overlap" option, which basically asks a ticker to alter/back off on other priorities and requests to meet this one (as in it deserves priority!). To implement it, there'd need to be some pay of knowing the space a tick label would use on the canvas and if there are overlaps to relax some other constraint (in the simplest case, simply downgrade every second tick to a minor (unlabelled) tick for example).

This differs IMHO from all other features herein listed, in that it seeks to use internal knowledge of the canvas, the tick fonts, sizes, and space they'd use to produce a pleasing outcome automatically if requested (by other means) to draw tick labels that would overlap (which it's hard to imagine anyone would value).

**Comment by mattpap** [comment]
@bernd-wechner, you should look into axis labeling policies (`Axis.major_label_policy`). This is a fairly new and badly documented feature, that covers this subject.

**Comment by bernd-wechner** [comment]
> Axis.major_label_policy

Thanks for the tip. Much appreciated. But indeed, poorly documented:

https://docs.bokeh.org/en/2.4.0/docs/reference/models/axes.html#bokeh.models.Axis.major_label_policy

Any tips on how to use it?
