### ISSUE TITLE
Documentation build improvements 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1688]
Docs build process needs several improvements:

* [x] sphinx `plot` extension directive to inline plots and code (#1694)
* [x] ~~galleries re-org / re-write~~ (#1689)
* [x] proper makefile dependencies (#1305)
* [x] sphinx `autoprops` extension to document Bokeh models (#1690)
* [x] correct (or at least better) version for deployed "dev" docs (#1692)
* [x] ~~split docs into separate repository?~~ (#1410)
* [x] ~~standalone tutorial build~~ (#1691)

@bokeh/dev anything to add to this list? Note this issue only concerns docs **build** issues, and not docs content.

**Comment by bryevdv** [comment]
Leaving galleries re-work for later
