### ISSUE TITLE
Docs build improvements 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1892]
* [ ] improve  sphinx `plot` extension directive
* [ ] galleries re-org / re-write (#1689)
* [x] ~~~split docs into separate repository?~~~ (#1410)
* [x] ~~~standalone tutorial build~~~ (#1691)

**Comment by fpliger** [comment]
ping @bryevdv . Can you check if any of those subtasks have been closed already? there were some significant improvements to docs recently...

**Comment by bryevdv** [comment]
None of these have been addressed, there is still more to to I will update this master PR today.

**Comment by bryevdv** [comment]
Most of this is no longer relevant, the part that still is has its own separate issue.
