### ISSUE TITLE
Server Cleanup

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#2029]
* [x] Use 12-factor app (http://12factor.net) conventions
 - [x] ENV var config (I like what https://github.com/fusic-com/flask-todo has done)
 - [x] log with unbuffered `stdout` (e.eprint) throughout
* [x] remove unused routes (#2188)
* [x] document all endpoints for `autohttp` (#2189)
* [x] endpoint/implementation split. (#2190)
 
 In general I'd like all the route functions to be as small as possible, and simply delegate to a plain function wherever possible, so that the simple function can be unit-tested

* [x] separate unit tests (no running server) from integration test (actually running servers)
* [ ] full deployment walkthroughs (including supervisors, log managers, setup screenshots etc)
 - [ ] Heroku (#2191)
 - [ ] AWS (#2192)
 - [ ] Conda Cluster (#2197)
 - [ ] Generic Linux Server (#2193)
* [x] split `bokeh_server` into its own package(#2194)
* [x] LDAP auth backend (#2195)

@almarklein @hhuuggoo @tswicegood @mattpap What else can we add to this list? Making server deployments easy and bulletproof is one of the most important tasks for the next few months.

**Comment by tswicegood** [comment]
> log with unbuffered stdout (e.eprint) throughout

@bryevdv not sure if you mean to configure the `logging` module to print to stdout or not, but that would be my recommendation.  That allows you to easily (for certain values of easy) redirect output to another server by changing the configuration.

> endpoint/implementation split.
>
> In general I'd like all the route functions to be as small as possible, and simply delegate to a plain function wherever possible, so that the simple function can be unit-tested

Huge :+1: on splitting implementation and routes.  The unit tests for those should for whatever is needed in the context of parsing/understanding the HTTP request and that they delegate to the correct implementation.  If you do that, your need for integration tests are very minimal.  Completely tested implementation that you know are dispatched to via mocking mean you generally don't need full integration testing other than for purposes of belts and suspenders-style testing.

**Comment by bryevdv** [comment]
@tswicegood yup that's all the idea :)

**Comment by hhuuggoo** [comment]
w.r.t config - we do have to allow some basic configuration via cmd line args.  I prefer python file based configuration (like we have) to env vars, but If you guys want to go env var I don't have a strong objection

blaze however needs to be configured using a python file - this is because blaze allows for defining in memory datasets, and you can't do that via env vars (also it would be very cumbersome)

**Comment by hhuuggoo** [comment]
The other thing is to re-think and simplify how we deal with curdoc, push, show etc.. but maybe that is a separate issue

**Comment by birdsarah** [comment]
I hope this is an appropriate place for this comment. Configuration of Cross Origin things would be great.

**Comment by hhuuggoo** [comment]
@birdsarah what kind of crossdomain config?

**Comment by bryevdv** [comment]
@hhuuggoo yes separate PRs I am going to make issues for these today. Can you maybe just list any routes you know to be obsolete offhand, and we will start with that?

**Comment by bkreider** [comment]
Please add this issue to this: #2197.

**Comment by bryevdv** [comment]
Old server is gone, other issues cover create deploy docs for new server.
