### ISSUE TITLE
Examples failures

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#2278]
* [x] Several mpl examples broken #2286
  * ~~subplots: missing pointa and short line (no jsconsole log) (not reproducible)~~
  * [x] list_collections: no plot, jsconsole: ```Uncaught TypeError: Failed to execute 'setLineDash' on 'CanvasRenderingContext2D': The 1st argument is neither an array, nor does it have indexed properties.```
  * [x] lc_offsets: same as above
* [x] glyph/calendar.py is broken (OK in firefox but not in chrome for me) (error description on comments below) #2286
* [x] glyph/sprint  is broken (not showing the hover, no jsconsole errors)
* [ ] glyph/buttons_server.py have dropdown red button looking bad (cut) in Chrome (see error description below)
* [x] glyph.ipynb is broken, cell number 5 throws ```DataRande1d``` error (error description on comments below)
* ~~[ ] glyph/donut.py has a missin wedge (white space at 10 o'clock) (not reproducible)~~
* [x] glyph/trail.py the box selection is not working... if we know about this (I remember something), we need to delete the boxselect tool from the example.
* [x] in plotting/server/census.py and plotting/server/abstractrendering.py there are fails on isocountours (not rendering)
* [ ] embed/publishing not showing the plot after auth, no py neither js error
* ~~[ ] embed/app_reveal.py with cross-origin issues (is working on firefox but not in chrome) (not reproducible)~~
* [ ] firefox: gyphs/widget_server.py, known issue in column length
* [x] compat/seaborn are broken: violin, kde
* ~~ggplot.ipynb has to be moved from seaborn into ggplot folder (artifact from testing)~~
* [x] most of the charts example under /charts have to be relocated to charts/file to be in sync with plotting folder
* [ ] lot of charts don't have x labels, but that's for later
* [ ] #1107 installation and instructions work ok on `unix` and not `windows` or `mac`

* [x] Zoom broken on image_url.py
* [x] `plotting\server\hover.py` crosshair and hover tool checkboxes not working
* [ ] `examples/plotting/server/remote_image.py`

```
Using saved session configuration for http://localhost:5006/
To override, pass 'load_from_config=False' to Session
Traceback (most recent call last):
  File "../../examples/plotting/server/remote_image.py", line 23, in <module>
    source.from_blaze(d.array, local=True)
  File "C:\Anaconda\envs\py27_conda_clean\lib\site-packages\blaze\expr\expressio
ns.py", line 165, in __getattr__
    result = object.__getattribute__(self, key)
AttributeError: 'InteractiveSymbol' object has no attribute 'array'
```
* [x] `app_reveal.py` (animated plot not animating, OK on IE)
* [ ] crossfilter filtering by continuous field on IE raises the following error when range is selected: 
```SCRIPT7002: XMLHttpRequest: Network Error 0x2efe, Could not complete the operation due to error 00002efe. ```
* [x]  HBox behaves unexpectly on resize (responsive)

* [x] angle_units doesn't work (math.pi instead of math.PI)
* [x] change to get rid of "Plot" as default title got lost

* [x] Examples/bokeh/charts/file//hover_span.py

```
(testconda)[scripts](master) python interactive_tester.py -l /home/damian/miniconda3/envs/testconda/Examples/bokeh/charts/file/
Running examples in custom location: /home/damian/miniconda3/envs/testconda/Examples/bokeh/charts/file/
cleaning previous session file...
OK

Opening home/damian/miniconda3/envs/testconda/Examples/bokeh/charts/file//hover_span.py

Traceback (most recent call last):
  File "/home/damian/miniconda3/envs/testconda/Examples/bokeh/charts/file//hover_span.py", line 8, in <module>
    from py import path
ImportError: No module named 'py'
```

**Comment by damianavila** [comment]
@bokeh/core collecting failures on this issue...

**Comment by damianavila** [comment]
Several mpl examples broken:

* subplots: missing pointa and short line (no jsconsole log)
* list_collections: no plot, jsconsole:
``` 
Uncaught TypeError: Failed to execute 'setLineDash' on 'CanvasRenderingContext2D': The 1st argument is neither an array, nor does it have indexed properties.
```
* lc_offsets: same as above

**Comment by damianavila** [comment]
glyph/calendar.py is broken too:
```
bokeh: setting prefix to /
calendars.html:193 Bokeh: setting log level to: 'info'
calendars.html:188 Bokeh: Realizing plot:
calendars.html:188 Bokeh:  - modeltype: PlotContext
calendars.html:188 Bokeh:  - modelid: 7405863d-305f-498c-9372-a37a7fc58a0d
calendars.html:188 Bokeh:  - elementid: be0f2639-1aa2-47df-a037-a5b4d46999a5
12calendars.html:194 Uncaught TypeError: Failed to execute 'setLineDash' on 'CanvasRenderingContext2D': The 1st argument is neither an array, nor does it have indexed properties.
12calendars.html:199 Uncaught TypeError: Cannot read property '1' of undefined
3calendars.html:199 Uncaught TypeError: Cannot read property '0' of undefined
4calendars.html:199 Uncaught TypeError: Cannot read property '1' of undefined
```

**Comment by damianavila** [comment]
glyph/sprint too... not showing the hover... no jsconsole errors...

**Comment by damianavila** [comment]
glyph/buttons_server.py have dropdow red button looking bad (cut) in Chrome.
Js console:
```
okeh: setting prefix to /
bokeh.js:43725 Bokeh: setting log level to: 'info'
bokeh.js:27938 Uncaught Error: cannot call methods on button prior to initialization; attempted to call method 'toggle'
jsnlog.js.map:1 GET http://localhost:5006/bokehjs/static/js/jsnlog.js.map 404 (NOT FOUND)
```

**Comment by bryevdv** [comment]
Weird `glyphs/calendar.py` and MPL examples are working for me (from master)

**Comment by damianavila** [comment]
glyph.ipynb is broken, cell number 5 throws:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-0d01e3eb2325> in <module>()
      1 source = ColumnDataSource(data=dict(x=x, y=y))
----> 2 xdr = DataRange1d(sources=[source.columns("x")])
      3 ydr = DataRange1d(sources=[source.columns("y")])

/home/damian/miniconda3/envs/testconda/lib/python3.4/site-packages/bokeh/plot_object.py in __init__(self, **kwargs)
     87 
     88         if not block_events:
---> 89             super(PlotObject, self).__init__(**kwargs)
     90             self.setup_events()
     91         else:

/home/damian/miniconda3/envs/testconda/lib/python3.4/site-packages/bokeh/properties.py in __init__(self, **properties)
    310 
    311         for name, value in properties.items():
--> 312             setattr(self, name, value)
    313 
    314     def __setattr__(self, name, value):

/home/damian/miniconda3/envs/testconda/lib/python3.4/site-packages/bokeh/properties.py in __setattr__(self, name, value)
    324 
    325             raise AttributeError("unexpected attribute '%s' to %s, %s attributes are %s" %
--> 326                 (name, self.__class__.__name__, text, nice_join(matches)))
    327 
    328     def clone(self):

AttributeError: unexpected attribute 'sources' to DataRange1d, possible attributes are end, name, names, range_padding, renderers, session, start or tags
```

**Comment by damianavila** [comment]
> Weird glyphs/calendar.py and MPL examples are working for me (from master)

Maybe was solved... I will test it on master in a little bit...

**Comment by damianavila** [comment]
but... wait... was something merged after my build?? OK... I will check master now...

**Comment by bryevdv** [comment]
DataRange1d is simple fix (remove args), thought we had caught all those at this point. hover chart also working on master. I will test with RC later tonight when I get home, I thought my current master was the same as the build (except some docs)

**Comment by damianavila** [comment]
glyph/donut.py has a missin wedge (white space at 10 o'clock)

**Comment by damianavila** [comment]
glyph/trail.py the box selection is not working... if we know about this (I remember something), we need to delete the boxselect tool from the example.

jsconsole:
```
Bokeh: setting prefix to /
trail.html:193 Bokeh: setting log level to: 'info'
trail.html:188 Bokeh: Realizing plot:
trail.html:188 Bokeh:  - modeltype: PlotContext
trail.html:188 Bokeh:  - modelid: af54ed8d-3ced-4291-8ac8-5407739bb398
trail.html:188 Bokeh:  - elementid: fb5780cc-6840-4557-8851-20e1d2fa0ff4
trail.html:188 Bokeh: 'rect' selection not available for Patches
2trail.html:188 Bokeh: 'rect' selection not available for Linetrail.html:188 18.i.cerrortrail.html:188 18.i.sendLogItemsConsoletrail.html:188 18.r.sendBatchtrail.html:188 18.r.logtrail.html:188 18.t.logtrail.html:188 18.t.errortrail.html:196 86.e.hit_testtrail.html:197 87.e.hit_testtrail.html:194 57.e.selecttrail.html:203 160.e._selecttrail.html:203 160.e._pan_endtrail.html:170 1.ctrail.html:170 1.e.Events.triggertrail.html:194 66.e._triggertrail.html:194 66.e._pan_endtrail.html:194 (anonymous function)trail.html:171 2.st.emittrail.html:170 etrail.html:170 2.G.emittrail.html:171 2.c.emittrail.html:170 2.G.tryEmittrail.html:170 2.G.recognizetrail.html:171 2.st.recognizetrail.html:170 Ttrail.html:170 2.c.handlertrail.html:170 2.domHandler
```

**Comment by damianavila** [comment]
I can confirm that mpl/subplot.py is working...

**Comment by damianavila** [comment]
btw, glyph/calendar.py is not working for me from master neither

**Comment by damianavila** [comment]
in plotting/server/census.py and plotting/server/abstractrendering.py there are fails on isocountours (not rendering).

jsconsole:
```
Bokeh: setting prefix to /
bokeh.js:43725Bokeh: setting log level to: 'info'
jsnlog.js.map:1 GET http://localhost:5006/bokehjs/static/js/jsnlog.js.map 404 (NOT FOUND)
bokeh.js:41458 'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead.
3bokeh.js:37461 Bokeh: could not set initial ranges
bokeh.js:36313 POST http://localhost:5006/render/b793c76c-9e15-484a-82ed-648540a6a9d1/b009f9ca-c835-497d-8a34-5c2b414c0da5/f92b7bb6-c527-444a-9367-3c5315316181 500 (INTERNAL SERVER ERROR)
```

**Comment by damianavila** [comment]
embed/publishing not showing the plot after auth, no py neither js error

**Comment by damianavila** [comment]
embed/app_reveal.py with cross-origin issues

jsconsole:
```
XMLHttpRequest cannot load http://localhost:5006/bokeh/objinfo/a510a2f9-cb70-4d1b-ad27-56ae5136aed2/70aad194-2407-4794-8ed3-53c4e726bef0. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:5000' is therefore not allowed access. The response had HTTP status code 401.
```

**Comment by damianavila** [comment]
firefox: gyphs/widget_server.py, known issue in column length...

**Comment by damianavila** [comment]
firefox: glyph/calendar.py works OK in firefox but not in chrome for me...

**Comment by damianavila** [comment]
Some of the compat/seaborn are also broken: violin, kde, sinerror

**Comment by damianavila** [comment]
Also ggplot.ipynb has to be moved from seaborn into ggplot folder.

**Comment by damianavila** [comment]
Also most of the charts example under `/charts` have to be relocated to `charts/file` to be in sync with `plotting` folder...

**Comment by damianavila** [comment]
Additionally a lot of charts don't have x labels, but that's for later (the relocation probably too).

**Comment by damianavila** [comment]
firefox: embed/app_reveal.py is working on firefox but not in chrome...

**Comment by fpliger** [comment]
@damianavila I've closed the calendars and compat/seaborn issues as I've tested ok both on OS X and Windows with all browsers. Please re-open those if they are not ok on your env.

**Comment by fpliger** [comment]
embed/publishing works ok for me from created `publishing.html` but not if I login to bokeh-server with the right user..

**Comment by damianavila** [comment]
Migrating all the unresolved problems to independent new issues. Closing here...
