### ISSUE TITLE
Geo ToDo

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3148]
@bryevdv and I sketched out a series of things that need to happen to make geo work "as expected" (a fairly subjective set of things that you would expect bokeh to be capable of).

This issue just collects them all, the plan is to make them a series of as small as possible PRs.

In 0.11:
- [x] Move columns properties from DataSource to ColumnDataSource (not all data sources are columnar) #3150
- [x] New GeoJSONDataSource. Python side (inherits from DataSource), BokehJS side (inherits from ColumnDataSource for now - see below). #3152
- [x] max zoom - #3175
- [x] min zoom 
- [ ] Patches with hole - #3399 
- [x] +/- zoom buttons
- [x] Mapped axes (so can, for example, display lat lon when plot is projected)
- [x] Color map
- [ ] Plot projections
- [x] Fixed aspect ratio ranges (solves resize and wheel zoom issues)
- [ ] GeoJSONSpec should do GeoJSON validation
- [ ] Add "Making Maps" section to user guide (@brendancol)

Second tranche:
- [ ] zoom with some kind of controllable rate (would feed back into tile-renderer)
- [ ] remote GeoJSON data source (pass in a geojson url) 
- [ ] Hover gets gross on things like zoomed in states - may want a fixed position box for display
- [ ] Topojson (ok to deprioritize - but it's a pretty useful thing and I don't think that hard to support)

Re-factor GlyphRenderer and bits of Glyph so can plug-in non-columnar data sources (see notes here: https://github.com/bokeh/bokeh/wiki/Geo-Ramblings#renderers--non-columnar-data-sources) and then:

Third tranche:
- [ ] Re-do GeoJSONDataSource to not inherit from ColumnDataSource and to be able to represent itself in a way that is natural for it.
- [ ] SyntheticDataSources that allow you to give two different data sources that are driving one glyph.

This last part will be much more broadly useful but its last because we can get a lot of cheap wins by doing the ColumnDataSource version of GeoJSON and then getting all the other pieces of the geo puzzle in place.

Other:
- [x] axes in Degrees/Minutes/Seconds
- [ ] handle MultiPoint

**Comment by rothnic** [comment]
Just wanted to post this here for reference since you are working on it. For maps, I highly recommend taking a look at [cesium](http://cesiumjs.org/) as a potential target. Their map is the best open source web-based map I have seen, and it can ingest geojson, but their primary source is [CZML](https://github.com/AnalyticalGraphicsInc/cesium/wiki/CZML-Guide). I believe the main difference is czml is designed to describe time varying geographical scenes in 3D. Another potential use is that they have an extensive library written in javascript for coordinate transforms, etc.

Also, as an architectural topic, to me it seems like GeoJSON and any of these GIS formats are a little bit different than the standard data source. I think that is why you run into the columnar issue. Do we have other data sources that actually have serialized graphical representations in them? To me, it would seem equivalent as to having a VegaDataSource. This may be ok, it just seems a little strange.

**Comment by brendancol** [comment]
I see GIS data as a natural fit for a columnar data source as long as there is a first-class Geometry or Shape column type which is how spatial data is handled in postgis, mysql, mssql etc.

**Comment by bryevdv** [comment]
Closing this, most new GIS support should/will go in GeoViews, with any specific new features in stable core bokeh being driven by requirements there.
