### ISSUE TITLE
Known pending issues/tasks for 0.11 release

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#3390]
ping @bokeh/core 

**NOTE**: Please collect all small pieces of work in this PR: https://github.com/bokeh/bokeh/pull/3497

Bugs
-----
These are all issues in the core library. A few are really must-fix:

* [x] bokeh.js must load before widgets, compiler(#3500)
* [x] upload bokeh-compiler[.min].js to CDN (#3491)
* [x] ~~~notebook + server does not work~~~ (#3461) MARKED AS KNOWN ISSUE
* [x] opening multiple tabs/reloading individual client apps broken (#3472) (now issue PR)

A few more are should-fix if we can, especially if the fix is small:

* [x] ESC does not clear selections (#3465)
* [x] Hover tool performance seems degraded (#3467)
* [x] Can't turn wheel zoom back on (#3469)

The last ones are not as important, but if brief investigation reveals a trivial/one-line, self-contained fix, it could be considered (or if not, possibly delete the demo):

* [x] boxplot whisker, marker style ignored (#3462)
* [x] Reveal slideshow does not work at all *suggest DELETE it* (#3463)
* [ ] `maps_cities.py` data disappears after pan (#3464)
* [x] `dynamic_map.py` data overlay dislodged after pan/zoom (#3466)
* [ ] `embed_responsive_with_height.py` starts out wrong size (#3468)
* [x] `airports_map.py` and `iris_splom.py` can't pan or zoom in/out in cases that should work (#3470)
* [x] don't leak user path info in BokehJS (#3488)

Demo Issues
----

These are all issues (mostly very small) in demos that can be improved:

* [x] ~~~pandas deprecations~~~ (requires too-new pandas)
 - examples/charts/file/donut.py
 - examples/charts/file/histogram_single.py
 - examples/charts/file/scatter_multi.py
 - examples/charts/file/stacked_bar.py
 - examples/charts/notebook/scatter.ipynb
 - examples/glyphs/daylight.py
 - examples/plotting/file/periodic.py
* [ ] layout/visuals odd?
 - examples/charts/file/line_multi.py
 - examples/charts/file/scatter_multi.py
 - examples/glyphs/custom.py
* [x] still has legacy charts!
 - examples/charts/notebook/dots.ipynb
 - examples/charts/notebook/Horizon.ipynb
 - examples/charts/notebook/palettes.ipynb
 - examples/charts/notebook/steps.ipynb
 - examples/charts/notebook/timeseries.ipynb
* [ ] ColumnDataSource dataframe deprecation
 - examples/glyphs/data_tables_server.py
* [x] Just delete
 - examples/glyphs/prim_server.py
* [x] ~~~MPL deprecations?~~~ (upstream, nothing we can do)
 - ggplot examples
 - seaborn examples
* [x] Update instructions for CORS stuff
 - examples/embed/animated.py
 - examples/embed/widget.py
* [x] update rate should be increased for examples/embed/animated.py
* [x] browserlib deprecation in examples/embed/embed_multiple.py
* [x] examples/glyphs/iris_splom.py  has missing text labels, excessive borders
* [x] examples/plotting/server/geojson_points.py has ugly random data, too fast update
* [x] examples/glyphs/taylor_server.py should fix range, move legend

Tasks
----

* [x] dev build / RC1
* [x] SERVER DOCS
* [ ] Server benchmarking 
* [x] Deploy server examples on demo.bokehplots.com
* [ ] YouTube video demos and tutorials
* [x] Better organize reference guide
* [ ] Better organize dev guide guide
* [ ] Test matrix coverage (esp. package upgrade checks)
* [ ] Static site final work
* [x] Gallery curation
* [x] Coordinate for Anaconda repo 
* [ ] Blog post
* [x] Mailing list announcement
* [x] Tweets and schedule
* [x] Review all notebooks in `bokeh-notebooks`
* [x] Finish Django "Happiness" example for `bokeh-demos`
* [ ] Flask example for `bokeh-demos`?
* [ ] New App examples
 - [ ] GitHub Explorer
 - [ ] App with Numba
 - [x] Weather example (@jbrail)
 - [ ] New crossfilter (@brendancol)
 - [ ] Redis integration 
 - [ ] simple downsampling
* [ ] new UDF examples
* [x] new `push_notebook` examples
* [x] flake8-ing the examples
* [x] READMEs all over examples
* [x] silence sphinx warnings
* [x] release notes + migration guide

**Comment by fpliger** [comment]
ping @bryevdv

**Comment by damianavila** [comment]
ping @bokeh/core :wink:

**Comment by fpliger** [comment]
jeje... right, sorry. mind biased as it was a follow up of a quick in office discussion. :)

**Comment by birdsarah** [comment]
gapminder example is broken. `interactions/interactive_bubble/gapminder.py`

It will be affected by @mattpap's change on #3437 - would be really great to have a docstring update about that change too.

But is currently failing with the error:
````python
Traceback (most recent call last):
  File "gapminder.py", line 67, in <module>
    xaxis = LinearAxis(SingleIntervalTicker(interval=1), axis_label="Children per woman (total fertility)", **AXIS_FORMATS)
TypeError: __init__() takes 1 positional argument but 2 were given
`````

**Comment by bryevdv** [comment]
Might need "ticker=" for arg now

**Comment by birdsarah** [comment]
Thanks @bryevdv, fixed on `docs_ex_011_3` in #3497.

**Comment by bryevdv** [comment]
That info could probably go in the migration guide.

**Comment by bryevdv** [comment]
I'm not actually sure why it worked without it before, though, to be honest.

**Comment by birdsarah** [comment]
@boeh/dev there are a two plots broken in the docs. I have listed them on #3404, but thought I should mention them here too:
* user_guide/geo.html broken
* user_guide/interaction.html - CustomJS with a Python function example is broken - needs to be built with python 3

**Comment by almarklein** [comment]
Actually, the example for the "CustomJS with a Python function" does not build because PyScript (i.e. the inspect module) cannot obtain the source code of the function during the doc building.

**Comment by bryevdv** [comment]
We will have to do a hand deploy of the docs built with py3. (Will want to keep updating them anyway)

**Comment by hsparra** [comment]
I must say I like the new look of the docs.

**Comment by nothinkelse** [comment]
Hi. I would like to try downsampling (on server) of large time-series of data, such that only relevant data is sent to client. I understand that with 0.11 there is a new Tornado server. What is a status of down-sampling for the new bokeh server implementation? Is it implemented, just not documented? If so can somebody give a hint how to try it out? Also I read somewhere about plans of sending data to client in binary format, is this on the road map?

**Comment by bryevdv** [comment]
Closing this, will open new epic or burn list for `0.12`
