### ISSUE TITLE
Trim BokehJS size and reduce code duplication

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#673]
Some ideas (to be explored in separate sub-issues):

* [x] split off bokehjs-widgets
* [x] ~~remove license comments~~ (#674) (reverted)
* [x] ~~test closure compiler~~ (https://github.com/bokeh/bokeh/issues/673#issuecomment-61482112)
* [ ] add explicit returns everywhere
* [x] consolidate some modules 
* [x] `defaults`/`display_defaults` duplication (fixed in #1225)
* [x] factor `gmap_plot`

Others?

**Comment by rothnic** [comment]
Have you considered [webpack](http://webpack.github.io/)? It seems like you wouldn't ever use all of bokehjs, so by using node style 'require', even for styles, you can modularize the code. Webpack then compiles all required dependencies together.

Another project that has this problem, but don't know if they solved it, is cesium.js. They are around the 5mB range.

**Comment by bryevdv** [comment]
I believe we are potentially looking at browserify for the future. ping @tswicegood

**Comment by tswicegood** [comment]
I'm definitely +1 on [browserify][].  That would remove a little bit of the boilerplate, but not all of it.  Making sure that Bokeh is npm installable, however, does mean that people can assemble their own version of bokeh.js and compile it themselves.  We would just need to keep a close eye on how modular the various pieces are.  So long as there aren't many (any) cross-module dependencies you can let someone build as much as they need.

Note: I'm saying this in the abstract, I haven't looked at the code in depth to know how reasonable it is to enforce that level of separation across modules.

[browserify]: http://browserify.org

**Comment by bryevdv** [comment]
The tasks in this issue were largely completed long ago. I am going to open new specific issues and an epic for performance and space optimiations soon
