### ISSUE TITLE
Changes right at 2.0 release

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#8666]
* [x] #8998 remove noarch spec, update conda build process
* [x] Update SITEMAP_BASE_URL
* [x] update Travis CONDA_REQS `"conda=4.7.12 conda-build=3.18.10 conda-verify=3.4.2 ripgrep=0.10.0"`
* [x] #8996 update classifiers and pytho_requires
* [x] #8938 remove python 2 and 3.4 from the test matrix
* [x] #8946 remove dependency on six
* [x] #8949 remove bokeh.util.future
* [x] #8951 remove future imports
* [x] #8958 remove superfluous string funds
* [x] #8956 remove `legacy_datetime64` cruft
* [x] #8962 simplify `super`
* [x] #8966 `use_strict` defaults to true 
* [x] #8969 drop python 2 and 3.4 support
* [x] #8972 sphinext options described in #8665 can be removed (from setup and conf.py), as well as `PLOT_PAGE`
* [x] #8964 remove things that could be marked deprecated up until now
* [x] #8979 remove protocol versioning
* [x] #8985 strict hover formatter specs
* [ ] split off IE compat bundle
* [x] #8973 change tile_provider module attributes to enums
* [x] #9030 fix up `RemoteDataSource` hierarchy (NEEDS MIGRATION NOTE)
* [x] #8936 remove `h_symmetry`, `v_symmetry`
* [x] #8935 tornado 5.0 min? 
* [x] ~~only support networkx >=2.0~~
* [ ] prune some ancient docs versions
* [x] ~~remove PolySelectTool?~~
* [ ] remove CDS.callback in favor of uniform events (do this in general for all old ad-hoc callbacks)
* [x] #8968 make selection *instances* read only (selections can be modified but not replaced)
* [x] #8975 drop selection "dict" compat 0d, 1d, etc
* [x] #8968 make CDS `.data` not settable from other CDS (only plain dict)
* [x] #8942 Add Pillow as a dependency
* [x] move tests out-of-tree? (maybe start using tox for testing)
* [x] #8990 `Line` and `Patch` should switch to scalar props (other places need scalar props?)
* [ ] make `bokeh.plotting.helpers` be a private module
* [x] #8986 make slider `value` update always immediately and `value_throttled` accroding to policy

**Comment by bryevdv** [comment]
@bokeh/dev I would also like to make a statement to the effect that anything before Bokeh 0.11 is officially "obsoleted". Thoughts?

**Comment by mattpap** [comment]
> I would also like to make a statement to the effect that anything before Bokeh 0.11 is officially "obsoleted". Thoughts?

What does "obsoleted" mean in in this context? What do we guarantee regarding 0.12 and 0.13 (and possibly 1.0.x) branches?

**Comment by bryevdv** [comment]
> What does "obsoleted" mean in in this context? What do we guarantee regarding 0.12 and 0.13 (and possibly 1.0.x) branches?

Nothing specifically, but I want to give people nudge to keep more up to date. If you want something specific, it could mean that docs for those versions will no longer be hosted (we still have 0.11 docs up for instance)

**Comment by bryevdv** [comment]
@mattpap I've removed "try using Python enums in some way"  but let me know if you have any other specific ideas

**Comment by bryevdv** [comment]
I put up and tweeted a poll about `PolySelectTool` https://discourse.bokeh.org/t/remove-polyselecttool-for-2-0/3660 It seems some folks do use it so I guess we will keep it for now, warts and all.

**Comment by bryevdv** [comment]
I'm going to go ahead and close this issue. This was mainly to keep track of things on `landing-2.0` anything remaining we an just track as normal
